"""
Django settings for test_project project.

Generated by 'django-admin startproject' using Django 6.0.dev20250312034749.

For more information on this file, see
https://docs.djangoproject.com/en/dev/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/dev/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/dev/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-7d%&hlq-cy79k8ll6is#7a)%!7$vp_u##ky%92qa-aouc0gpkz'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
################################## PAYBUILDR #########################################
    # Required dependencies
    'rest_framework',
    # Your package - make sure this matches your app config
    'stripe_kong.apps.StripeKongConfig',  # or just 'stripe_kong'
################################## END PAYBUILDR #########################################
]


################################## PAYBUILDR #########################################
# pull these from stripe dev test mode dashboard
STRIPE_SECRET_KEY = 'sk_test_asdf'  # Use a Stripe test key
STRIPE_PUBLIC_KEY = 'pk_test_asdf'
STRIPE_WEBHOOK_SECRET = 'whsec_asdf'
# start the stripe cli
STRIPE_SUCCESS_URL = 'http://localhost:8060/webhook/success/'
STRIPE_CANCEL_URL = 'http://localhost:8060/webhook/cancel/'
# start kong
KONG_ADMIN_URL = 'http://localhost:8001'  # Adjust if you have Kong running elsewhere
KONG_SYNC_ENABLED = True
# optionally start httpbin in docker compose to start whipping up some test API
PUCK_SETTINGS = {
    'EDITOR_ENABLED': True,  # Set to False in production to disable the editor
    'STATIC_URL_PATH': 'stripe_kong/js/puck/dist/',
}
################################## END PAYBUILDR #########################################



MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'test_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'test_project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/dev/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/dev/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/dev/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/dev/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/dev/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
